p8105_hw2_yc4384
================
Yangyang Chen
2023-10-02

## Problem 1

**First:**

- Clean the data in `pols-month.csv`.
- Use `separate()` to break up the variable `mon` into integer variables
  `year`, `month`, and `day`.
- Replace month number with month name
- Create a `president` variable taking values `gop` and `dem`.
- Remove `prez_dem` and `prez_gop`; and remove the `day` variable.

``` r
pols_df = 
  read_csv("data/pols-month.csv") |> 
  janitor::clean_names() |> 
  separate(mon, into = c("year", "month", "day")) |> 
  mutate(month = month.abb[as.numeric(month)]) |> 
  mutate(president  = gov_dem) |> 
  select(-c(prez_dem,prez_gop)) |> 
  select(-day) 
```

    ## Rows: 822 Columns: 9
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl  (8): prez_gop, gov_gop, sen_gop, rep_gop, prez_dem, gov_dem, sen_dem, r...
    ## date (1): mon
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

**Second:**

- Clean the data in snp.csv using a similar process to the above.
- Arrange according to year and month.
- Organize so that `year` and `month` are the leading columns.

``` r
snp_df = 
  read_csv("data/snp.csv") |> 
  janitor::clean_names() |> 
  mutate(date = mdy(date)) |> 
  separate(date, into = c("year", "month", "day")) |> 
  mutate(month = month.abb[as.numeric(month)]) |> 
  mutate(year = ifelse(as.numeric(year) >= 2050 & as.numeric(year)<= 2068, as.numeric(year) - 100, as.numeric(year))) |> 
  select(-day,) |> 
  mutate(year = as.character(year)) |> 
  relocate(year, month)
```

    ## Rows: 787 Columns: 2
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (1): date
    ## dbl (1): close
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

**Third:**

- Tidy the unemployment data so that it can be merged with the previous
  datasets.
- This process will involve switching from “wide” to “long” format.
- Ensuring that key variables have the same name.
- Ensuring that key variables take the same values.

``` r
unemploy_df = 
  read_csv("data/unemployment.csv") |> 
  pivot_longer(
    Jan:Dec,
    names_to = "month",
    values_to = "unemploy_rate"
  ) |> 
  janitor::clean_names() |> 
  mutate(year = as.character(year)) |> 
  mutate(month = toTitleCase(month)) |> 
  relocate(year, month)
```

    ## Rows: 68 Columns: 13
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (13): Year, Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

**Date Description:**

- Join the datasets by merging snp into pols.
- Merging unemployment into the result.

``` r
prob1_df = 
pols_df |>  
  left_join(snp_df, by = c("year", "month")) |> 
  left_join(unemploy_df, by = c("year", "month"))
```

- **`pols_df`** contains 821 observations and ‘r ncol(pols_df)’
  variables, decribing the number of national politicians who are
  democratic or republican at any given time.

- **snp_df** contains 786 observations and ‘r ncol(snp_df)’ variables,
  describing Standard & Poor’s stock market index (S&P), often used as a
  representative measure of stock market as a whole.

- **unemploy_df** contains 815 observations and ‘r ncol(unemploy_df)’
  variables, describing the percentage of unemployment in each month of
  the associated year.

- **prob1_df** is the 822 \* 11 dimention result dataset, which contains
  821 observations and 10 variables. It ranges from 1947 to 2015. It’s
  variable conbined all key variables in **`pols_df`**, **snp_df** and
  **unemploy_df** datasets. including *year, month, gov_gop, sen_gop,
  rep_gop, gov_dem, sen_dem, rep_dem, president, close, unemploy_rate.*

## Problem 2

``` r
library(readxl)
```

**Dataset_1 - Mr. Trash Wheel:**

- Specify the sheet in the Excel file and to omit non-data entries (rows
  with notes / figures; columns containing notes) using arguments in
  `read_excel`.

- Use reasonable variable names.

- Omit rows that do not include dumpster-specific data.

- Update the data to include a new `homes_powered` variable based on
  this calculation.

``` r
trash_df = 
  read_excel("data/202207 Trash Wheel Collection Data.xlsx", range = "A2:N549") |> 
  janitor::clean_names() |> 
  drop_na(dumpster) |> 
  mutate(homes_powered_new = weight_tons*500/30) 
```

**Dataset_2 - Professor Trash Wheel:**

- Import, clean, and organize the data for Professor Trash Wheel.

``` r
prof_df = 
  read_excel("data/202207 Trash Wheel Collection Data.xlsx", sheet = 2, range = "A2:M96") |> 
  janitor::clean_names() |> 
  drop_na(dumpster) |> 
  mutate(homes_powered_new = weight_tons*500/30) 
```

**Dataset_3 - Gwynnda Trash Wheel:**

- Import, clean, and organize the data for Gwynnda Trash Wheel.

``` r
gwyn_df = 
  read_excel("data/202207 Trash Wheel Collection Data.xlsx", sheet = 4, range = "A2:K108") |> 
  janitor::clean_names() |> 
  drop_na(dumpster) |> 
  mutate(homes_powered_new = weight_tons*500/30) 
```

**Tidy Three Datasets and Combination:**

Tidy:

``` r
trash_df = 
  trash_df |> 
  mutate(name = "Mr.Trash") |> # dumpster_Mr_Trash = c(1:nrow(trash_df)-1)
  select(-c(homes_powered)) |> 
  mutate(date = as.character(date)) |> 
  mutate(year = as.character(year)) |> 
  relocate(name, dumpster)
```

``` r
prof_df =
  prof_df |> 
  mutate(name = "Prof.Trash") |> 
  select(-c(homes_powered)) |> 
  mutate(date = as.character(date)) |> 
  mutate(year = as.character(year)) |> 
  relocate(name, dumpster)
```

``` r
gwyn_df =
  gwyn_df |> 
  mutate(name = "Gwynnda_Trash") |> 
  select(-c(homes_powered))|> 
  mutate(date = as.character(date)) |> 
  mutate(year = as.character(year)) |>   
  relocate(name, dumpster)
```

Combination:

``` r
prob2_df = 
  trash_df |> 
  full_join(prof_df, by = c("name","dumpster","year","month","date","chip_bags","glass_bottles","grocery_bags", "weight_tons","volume_cubic_yards", "plastic_bottles", "polystyrene","cigarette_butts", "homes_powered_new")) |> 
  full_join(gwyn_df, by = c("name","dumpster","year","month","date", "weight_tons","volume_cubic_yards", "plastic_bottles", "polystyrene","cigarette_butts","homes_powered_new")) |> 
  mutate(date = as.Date(date, "%Y-%m-%d")) |> 
  arrange(date) |> 
  relocate(name, dumpster) 
```

**Data Description:**

- **prob2_df** contains 747 observations and 16 variables. Its key
  variables are *name, dumpster, month, year, date, weight_tons,
  volume_cubic_yards, plastic_bottles, polystyrene, cigarette_butts,
  glass_bottles, grocery_bags, chip_bags, sports_balls,
  homes_powered_new, plastic_bags*. The total weight of trash collected
  by Professor Trash Wheel are 3168.6666667. The total number of
  cigarette butts collected by Gwynnda in July of 2021 is 1.63^{4}

## Problem 3

1.  `MCI_baseline` data:

- Import and tidy data: Factorize sex and change it to a binary
  variable:

``` r
base_df = 
  read_csv("data/MCI_baseline.csv", skip = 1) |> 
  janitor::clean_names() |> 
  mutate(
    sex = 
      case_match(
      sex,
      1 ~ "male",
      0 ~ "female"), 
    sex = as.factor(sex)) |> 
  mutate(
    apoe4 = 
      case_match(
      apoe4,
      1 ~ "yes",
      0 ~ "no"), 
    sex = as.factor(sex)) 
```

    ## Rows: 483 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (1): Age at onset
    ## dbl (5): ID, Current Age, Sex, Education, apoe4
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

**Filter:** Participants whose age of onset were before baseline time:

``` r
  not_free_df = base_df |> filter(age_at_onset != "." & current_age > age_at_onset) 
  not_free_df
```

    ## # A tibble: 3 × 6
    ##      id current_age sex    education apoe4 age_at_onset
    ##   <dbl>       <dbl> <fct>      <dbl> <chr> <chr>       
    ## 1    72        62.9 male          16 yes   62.5        
    ## 2   283        69   male          16 no    68.3        
    ## 3   380        70.3 female        16 no    70.2

Delete them in baseline dataset:

``` r
  base_tidy_df = base_df  |> filter(!base_df$id %in% not_free_df$id)
```

**Data Pre-processing:**

- Step 1: Transformed binary variable of `sex` and `apoe4` to character
  variables.

- Step 2: Filtered participant who are free of MCI values in
  `age_at_onset`.

**Features of dataset `base_df`:**

- `base_df` dataset contains 6 key variables, including *id,
  current_age, sex, education, apoe4, age_at_onset*.

- There are 483 participants were recruited, and of these 97 develop
  MCI.

- The average baseline age is 65.0467909.

- The proportion of women in the study are APOE4 carriers: 0.3,

2.  Import, clean and tidy `mci_amyloid` data:

- Change error character type “Na” values into NA type.

- Modify `study_id` to `id` to ensure naming consistency.

``` r
amy_df = 
  read_csv("data/mci_amyloid.csv", skip = 1) |> 
  janitor::clean_names() |> 
  mutate( 
    baseline = replace(baseline, baseline == "Na", NA)
  )|> 
   mutate( 
    time_2 = replace(time_2, time_2 == "Na", NA)
  ) |> 
  mutate( 
    time_4 = replace(time_4, time_4 == "Na", NA)
  ) |> 
  mutate( 
    time_6 = replace(time_6, time_6 == "Na", NA)
  ) |> 
  mutate( 
    time_8 = replace(time_8, time_8 == "Na", NA)
  ) |> 
  mutate(id = study_id) |> 
  select(-study_id) |> 
  relocate(id)
```

    ## Rows: 487 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (5): Baseline, Time 2, Time 4, Time 6, Time 8
    ## dbl (1): Study ID
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

**Fix a problem:** As time\_# is speading across five columns, which
corresponding to five observation times, we should fix it using
`pivot_longer`:

``` r
amy_tidy_data = 
  pivot_longer(
    amy_df,
    baseline:time_8,
    names_to = "time_length",
    values_to = "time_value"
  )
```

**`amy_tidy_data`** is a 2435 \* 3 dataframe, containing 3 key
variables, including *id, time_length, time_value.*

3.  Check participants only aopear in the baseline or amyloid datasets:

``` r
only_in_base = setdiff(base_df$id, amy_tidy_data$id)
only_in_base 
```

    ## [1]  14  49  92 179 268 304 389 412

The participants 14, 49, 92, 179, 268, 304, 389, 412 only appeared in
the baseline data probably because they decided to move to a new
location from which they cannot easily reach the study center.

``` r
only_in_amyloid = setdiff(amy_tidy_data$id, base_df$id)
only_in_amyloid
```

    ##  [1] 484 485 486 487 488 489 490 491 492 493 494 495

The participants 484, 485, 486, 487, 488, 489, 490, 491, 492, 493, 494,
495 only appeared in the amyloid data probably because they entered the
study after few time from the baseline time.

``` r
prob3_df = inner_join(base_df, amy_tidy_data, by = "id")
```

**Describing resulting data:**

- The resulting dataframe **prob3_df** has 2375 observations with 8
  variables, which includes *id, current_age, sex, education, apoe4,
  age_at_onset, time_length, time_value*.

4.  Export data into data directory:

``` r
file_path = file.path("data", "MCI_Onset_Records.csv")
write.csv(prob3_df, file = file_path, row.names = TRUE)
```
